# Generated by Django 3.1.2 on 2020-11-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20201110_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
