# Generated by Django 3.1.2 on 2020-11-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0006_auto_20201031_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_alcohol', models.BooleanField(default=False)),
                ('serving_unit', models.CharField(max_length=10)),
                ('serving_size', models.FloatField()),
                ('calcium', models.FloatField()),
                ('calories', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('fat', models.FloatField()),
                ('fat_monounsatured', models.FloatField()),
                ('fat_polyunsaturated', models.FloatField()),
                ('fat_saturated', models.FloatField()),
                ('fat_trans', models.FloatField()),
                ('fibre', models.FloatField()),
                ('iron', models.FloatField()),
                ('potassium', models.FloatField()),
                ('protein', models.FloatField()),
                ('sodium', models.FloatField()),
                ('sugar', models.FloatField()),
                ('vitamin_a', models.FloatField()),
                ('vitamin_c', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('alcoholic', models.BooleanField()),
                ('time_tracked', models.DateTimeField()),
                ('daypart_associated', models.CharField(choices=[('BR', 'Breakfast'), ('MT', 'Morning Tea'), ('LN', 'Lunch'), ('AT', 'Afternoon Tea'), ('DN', 'Dinner'), ('SP', 'Supper')], max_length=2)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.user')),
            ],
        ),
        migrations.CreateModel(
            name='MacroGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_carbs', models.IntegerField()),
                ('target_protein', models.IntegerField()),
                ('target_fat', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.user')),
            ],
        ),
    ]
