# Generated by Django 3.1.2 on 2020-11-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='day_associated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='alcoholic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time_tracked',
            field=models.DateTimeField(null=True),
        ),
    ]
