# Generated by Django 3.1.2 on 2020-11-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('read_at', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
