# Generated by Django 3.1.2 on 2020-11-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201103_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
    ]
