# Generated by Django 3.1.2 on 2020-10-31 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20201031_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(default=65.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='signed_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='target_weight',
            field=models.IntegerField(default=67.5),
            preserve_default=False,
        ),
    ]
