# Generated by Django 3.1.2 on 2020-10-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_auto_20201031_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(),
        ),
    ]
