# Generated by Django 3.1.2 on 2020-11-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('lobby', '0006_auto_20201031_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourited_food',
            field=models.ManyToManyField(related_name='favourited_by', to='meals.Food'),
        ),
    ]
